[package]
name = "yabit"
version = "0.1.0"
authors = ["Benjamin Wasty <benny.wasty@gmail.com>"]

[dependencies]
chrono = { version = "0.2.25", features = ["serde"] }
clap = "2.20.0"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
enum_primitive = "0.1.1"
num = "0.1.36"
